[package]
name = "mm"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
rand_distr = "0.4"
plotters = "0.3"
plotters-backend = "0.3"

[dev-dependencies]
assert_approx_eq = "1.1.0"


[[bin]]
name = "mm"
path = "src/main.rs"



